version: "3.8"

services:
  webserver:
    restart: unless-stopped
    depends_on:
      - backend
      - auth-server
    image: nginx:alpine
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      backend:

  backend:
    restart: unless-stopped
    image: node:16-alpine
    volumes:
      - './backend-server:/app'
    working_dir: '/app'
    command: 'index.js'
    networks:
      backend:

  auth-server:
    depends_on:
      - redis
    restart: unless-stopped
    build:
      context: authorization-server
    environment:
      - PORT=80
      - RPC_URL=https://volta-rpc.energyweb.org/
      - CACHE_SERVER_URL=https://identitycache-dev.energyweb.org/v1
      - CACHE_SERVER_LOGIN_PRVKEY=eab5e5ccb983fad7bf7f5cb6b475a7aea95eff0c6523291b0c0ae38b5855459c
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - JWT_SECRET=asecretstring
      - ACCEPTED_ROLES=role1.roles.app-test2.apps.artur.iam.ewc
    networks:
      backend:

  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      - REDIS_PASSWORD=redis
    networks:
      backend:
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data:

networks:
  backend:
