version: "3.8"

services:
  webserver:
    restart: unless-stopped
    image: did-auth-proxy-webserver
    pull_policy: never
    build:
      context: nginx
    ports:
      - "127.0.0.1:8080:80"
    networks:
      dev-backend:
    volumes:
      - ./nginx/nginx.dev.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf
    extra_hosts:
      - host.docker.internal:host-gateway

  backend:
    restart: unless-stopped
    image: did-auth-proxy-backend
    pull_policy: never
    build:
      context: backend-server
    networks:
      dev-backend:

  redis:
    image: bitnami/redis:latest@sha256:25d8a8efc85d38b03e0ad6b8e565bfe529867e2a12c088a6b6f70535d713d8fb
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      dev-backend:
    volumes:
      - dev-redis-data:/bitnami/redis/data

  redis-commander:
    image: rediscommander/redis-commander:latest@sha256:19cd0c49f418779fa2822a0496c5e6516d0c792effc39ed20089e6268477e40a
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - REDIS_HOSTS=redis:redis:6379
    networks:
      dev-backend:

volumes:
  dev-redis-data:

networks:
  dev-backend:
